format = "$directory$git_status$direnv$git_branch$fill$custom$cmd_duration$time$line_break$character"
palette = "custom"

[[battery.display]]
threshold = 10

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold green)"
vimcmd_symbol = "[❮](bold blue)"

[cmd_duration]
format = "[  $duration ]($style)" # If you don't have a nerdfont on, this is a clock symbol
min_time = 30_000 # 30 seconds

[directory]
truncation_length = 4
truncate_to_repo = false # Show full path of current directory

[directory.substitutions]
"~/" = ""

[direnv]
disabled = false
format = "[$loaded]($style)"
loaded_msg = ""
unloaded_msg = "UNLOADED"

[fill]
style = "fg:fill"
symbol = "─"

[git_branch]
ignore_branches = [ "master", "main" ]

[git_status]
disabled = false
style = "white"
modified = "M"
staged = "S"
untracked = "A"
renamed = "R"
deleted = "D"
conflicted = "U"
stashed = ""
ahead = "[+$count](green)"
behind = "[-$count](red)"
diverged = "[+$ahead_count](green),[-$behind_count](red)"
format = """\
  [(\
    (\\[\
      [($conflicted)](orange)\
      [($stashed)](white)\
      [($staged)](blue)\
      [($deleted)](red)\
      [($renamed)](yellow)\
      [($modified)](yellow)\
      [($untracked)](green)\
    \\])\
    ( \\[$ahead_behind\\])\
    )]\
    ($style)"""

[nix_shell]
disabled = true

[package]
disabled = true

[palettes.custom]
fill = "#44475A"
orange = "#ff8800"
pink = "#ea76cb"

[time]
disabled = false
time_format = "%I:%M %p" # 9:47 PM
